#!/bin/bash

# Creates the RainbruRPG.html/ directory if needed
if [ ! -d RainbruRPG.html ]; then
   mkdir RainbruRPG.html/
else
   echo "RainbruRPG.html/ doesn't need to be created"	
fi

# Copy the htmlMakefile.am if needed
if [  ! -e RainbruRPG.html/Makefile.am ]; then
   cp htmlMakefile.am  RainbruRPG.html/Makefile.am
else
   echo "RainbruRPG.html/Makefile.am doesn't need to be copied"	
fi

# setting up compilation for GNU/Linux
cp configure.in.linux configure.in
cp Makefile.am.linux Makefile.am
cp common/Makefile.am.linux common/Makefile.am
cp maincore/Makefile.am.linux maincore/Makefile.am
cp ogreGui/Makefile.am.linux ogreGui/Makefile.am
cp client/Makefile.am.linux client/Makefile.am


automake
autoconf
