* Upgrade from Foswiki 1.1.2 to 1.1.5

I'm using the patch release upgrade, see 
http://foswiki.org/System/UpgradeGuide#Upgrading_to_a_new_patch_release

Go and download Foswiki-upgrade-1.1.5.tgz from
http://sourceforge.net/projects/foswiki/files/foswiki/1.1.5/Foswiki-upgrade-1.1.5.tgz

in the root dir of foswiki, run the command 
=tar --strip-components=1 -xvzpf Foswiki-upgrade-1.1.5.tgz=.

Update file ownership and permissions

  - [X] Visit bin/configure
    - [X] Check again your file/directories permissions
    - [X] Address any warnings or errors reported by the new configuration checkers
    - [X] Go to the Extensions, JQuery tab, Select the 1.7.1 version of jquery,
      ensure that a JQuery theme has been selected, Disable any JQuery plugins flagged as obsolete
  - [X] If you use the Foswiki Cache, be sure to refresh the cache. See System.PageCaching#Refreshing_the_cache

** Troubleshooting
- When in bin/configure, you see this error in your browser :
  =Use of uninitialized value in string eq at /home/rainbru/www/upgrade_foswiki/wiki/wiki/lib/Foswiki/Configure/Checkers/SMTP/Username.pm line 26.=
  - I personnaly have to add
  =$Foswiki::cfg{Email}{MailMethod} = 'Net::SMTP';=
  in the lib/LocalSite.cfg file.
  Add it to the end of LocalSite.cfg (but before the =1;= line.

- There are only 2 tabs in configure script output (Web Server Environment and
  General path settings), so cannot go to Extension tab for next step
  (Select the 1.7.1 version of jquery in the Extension/JQuery tab)
  - Was a problem in lib/LocalSite.cfg (forgotten the ; at the end of the
  =$Foswiki::cfg{Email}{MailMethod} = 'Net::SMTP'= line).

* Upgrade from Foswiki 1.1.5 to 1.1.7

Using a patch release

- Make sure you have an up-to-date CPAN::version running :
  =perl -Mversion -e 'print "$version::VERSION\n"'=
  it must eb at least 0.77
- Copy the upgrade patch to your foswiki root directory and issue :
  =tar --strip-components=1 -xvzpf Foswiki-upgrade-1.1.5.tgz=
  
  If you have several /Cannot utime: Permission denied/ message from tar, 
  it's not that important, files are overriden anyway

- Go to your bin/configure script and fix for files/directories permissions
  I personnaly had to :
    chmod 0777 -R data/
    chmod 0777 -R working/
  You also have to save once, to avoid the /PatternSkinTheme/ error.

- Go to Main.SitePreferences and add this setting
  =* Set PATTERNSKIN_JQUERY_THEME = PatternSkinTheme= in
- If you're using a cache functionality, refresh it :
  refresh cache (add ?refresh=all) to the url

** Troubleshooting

- Got a /Error: no such theme PatternSkinTheme/ error
    see http://foswiki.org/Support/Question1207
    Simply go to bin/configure and save or manually add the following in /LocalSite.cfg/
#+BEGIN_EXAMPLE
$Foswiki::cfg{JQueryPlugin}{Themes}{PatternSkinTheme}{Url} = '$Foswiki::cfg{PubUrlPath}/$Foswiki::cfg{SystemWebName}/PatternSkinTheme/jquery-ui.css';
$Foswiki::cfg{JQueryPlugin}{Themes}{PatternSkinTheme}{Enabled} = 1;
#+END_EXAMPLE

- Got an error in Sandbox main page

#+BEGIN_EXAMPLE
Could not perform search. Error was: Error in tempfile() using /home/project-web/rainbrurpg/cgi-bin/wiki/working/tmp/XXXXXXXXXX: Could not create temp file /home/project-web/rainbrurpg/cgi-bin/wiki/working/tmp/uDBAKwwTJ3: Permission denied at /home/project-web/rainbrurpg/cgi-bin/wiki/lib//Foswiki/Sandbox.pm line 506 at /usr/share/perl5/File/Temp.pm line 1381 
#+END_EXAMPLE
    Seems to be fixed by ?refresh=all
* Upgrade from Foswiki 1.1.7 to 1.1.8

This new Foswiki release fix a *Critical Security Vulnerability* in
Locale:Maketext, see http://foswiki.org/Support/SecurityAlert-CVE-2013-1666
for more informations.

Foswiki now need at least CPAN:version 0.77. My hosting provider
only has version 0.72, so we need to updgrade this before

** How to know the current version's version

Go to _configure_ script and go to the 'Web server environment' page.
Under the 'Perl modules' category, you can see the version item.

** Upgrade CPAN:version
Go to http://search.cpan.org/perldoc?version and download latest tar.gz.
This test was done with version 0.9902.

- Extract archive and go to the created directory: 
tar -xvf version-0.9902.tar.gz
cd version-0.9902/
- Create Makefile for perl only and call make
perl Makefile.PL --perl_only
make
- Copy new files to your LIB directory. The LIB directory is the 'lib/' 
directory, in your foswiki root, do not copy to Foswiki/lib/CPAN/lib, it
doesn't work. To be sure, go to bin/configure, in the 'Web server environment' 
page and search for the '@INC library path' : this is the first listed 
directory.

cd /blib/lib
cp -R version* /path-to-your-wiki/lib/

Go back to configure to check for the CPAN:version's version, this should
be 0.9902.

** Upgrading Foswiki

*** Install the upgrade package
Go and download the upgrade package :
http://sourceforge.net/projects/foswiki/files/foswiki/1.1.8/Foswiki-upgrade-1.1.8.tgz

Verify you're not running perl 5.16.x, if you are running it, please see
http://foswiki.org/Tasks/Item12413 for a patch.

Put the upgrade patch in the Foswiki root directory and issue the following 
command :
=tar --strip-components=1 -xvzpf Foswiki-upgrade-1.1.8.tgz=

*** Change directories permissions
- Go to your bin/configure script and fix for files/directories permissions
  I personnaly had to :
  chmod 0775 -R pub/
  chmod 0775 -R data/
  chmod 0775 -R working/
*** Refresh cache
    
Calling ?refresh=all

*** configure scripts warnings
**** Upgrade Locale::MakeText
Same way as used for CPAN:version
** Conclusion

You can see foswiki version in System.WebHome. Now it should be 1.1.8.
All is working just fine _out of the box_ so I don't have to write a 
*troubleshooting* section.

Test your installation : search, test sending a mail through the =configure=
script.
